### PR TITLE
Create taginfo.json

### PR DESCRIPTION
**Pull request by st3b1t**
after merge you need sending a PR to add `taginfo.json` here:
https://github.com/taginfo/taginfo-projects/blob/master/project_list.txt

in this way the project will be published here
image

### CODE REVIEW

**Comment by smartm0use** [comment]
Wait for it.
I need first to refactor some things, such as removing `payment:bitcoin` tag, that is deprecated!

Thank you ;)

**Comment by st3b1t** [comment]
> Wait for it. I need first to refactor some things, such as removing `payment:bitcoin` tag, that is deprecated!
> 
> Thank you ;)

ah mmmh I didn't know it! I read now in the wiki, I was left at the time of the old tagging...
https://wiki.openstreetmap.org/wiki/Key:currency

this seems a bit problematic to me, I can tell you from experience(the OSM community is not very responsive when it comes to deprecated tags) that probably many OSM users will continue to use this tag for some time yet, so perhaps if it exists it is better not to ignore it and possibly support the new one as a priority..

however `payment:bitcoin` made more maximalist :)   `XBT` is ugly

**Comment by smartm0use** [comment]
I agree. On my side I consider both tags for backwards compatibility.

**Comment by smartm0use** [comment]
Meanwhile I removed the references to `payment:bitcoin` from the information box in the footer of website.
You may update your PR to make me to merge it.

**Comment by st3b1t** [comment]
> Meanwhile I removed the references to `payment:bitcoin` from the information box in the footer of website. You may update your PR to make me to merge it.

ups I'm sorry..... I hadn't read the prev message!
In meanwhile I was adding a couple of optional features, they shouldn't break anything it's for more convenience.

**Comment by smartm0use** [comment]
Ok, I see.
But... what about taginfo.json file? Shouldn't you update it too?

**Pull request merged**
